### ISSUE TITLE
老哥，想问一下 Archive 页面文章数量如果修改

### ISSUE THREAD

**Issue by Solleter** [lotabout/hexo-theme-noise#12]
老哥，想问一下 Archive 页面文章数量如果修改，我在archive.pug代码里没找到数量相关的代码，现在 Archive 页面每页只能显示10篇文章，我想显示更多一点

**Comment by lotabout** [comment]
@Solleter 这个应该是 hexo 默认的选项，不是主题的，尝试下这个：

```# Pagination
archive_generator:
  per_page: 0
```

**Comment by Solleter** [comment]
> @Solleter 这个应该是 hexo 默认的选项，不是主题的，尝试下这个：
> 
> ```
> archive_generator:
>   per_page: 0
> ```

解决了，使用 archive_generator 可以实现这个效果，非常感谢
