### ISSUE TITLE
error: Cannot read property 'groupBy' of undefined

### ISSUE THREAD

**Issue by yunatseng** [lotabout/hexo-theme-noise#14]
The error occurs when i click the "Archives" buttons

![image](https://user-images.githubusercontent.com/8156364/89859453-a02b5c00-dbd3-11ea-9992-d517d2d7c83b.png)

I've tried to npm i lodash in my project but it seems not work QQ

![image](https://user-images.githubusercontent.com/8156364/89859543-cfda6400-dbd3-11ea-8f8e-6f7055ce3553.png)

could you give me some hint to solve the problem? 

thanks a lot! and nice theme!

**Comment by lotabout** [comment]
@effytseng Would you please try branch `ticket-14`?

**Comment by yunatseng** [comment]
@lotabout it works perfectly!! thanks!!! 💯
