### ISSUE TITLE
想使用 Archives 页面作为 Home 页面 有啥好建议吗 感谢

### ISSUE THREAD

**Issue by Aaaaaaron** [lotabout/hexo-theme-noise#16]

**Comment by Aaaaaaron** [comment]
想直接点进去就是这个页面 
![image](https://user-images.githubusercontent.com/15643702/91634764-72dd0b80-ea25-11ea-859d-88015325f5dc.png)

**Comment by lotabout** [comment]
Use the following settings in main `_config.yaml`:

```
per_page: 0
noise:
  compact_index: true
```
