### ISSUE TITLE
Something wrong about categories links

### ISSUE THREAD

**Issue by magicalne** [lotabout/hexo-theme-noise#3]
Hey,

First, thanks for your working on noise. I really like the layout and I use it on my blog.

Today I try to click on the categories links and they failed. I know the issue is on the url path. 

Reproduce:
1. Under **archives** page.
2. Click on the category link.
3. It will jump to **xxx/archives/categories/some-category**

I think the right url is the one without **archives**.

And I try to modify archive.jade and use **config.root** instead of **root**.
It works.

Maybe you already know this issue anyway.

Again, thanks bro.

**Comment by 0kaguya** [comment]
+1. e.g a category "bar baz" is localed at /categories/bar-baz/ but the link directs wrongly to the path /categories/bar baz/
